# Generated by Django 3.0.5 on 2020-10-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devk', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevkornerInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
            ],
        ),
    ]
