# Generated by Django 3.0.5 on 2020-10-16 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devk', '0004_devkornerinfos'),
    ]

    operations = [
        migrations.AddField(
            model_name='devkornerinfos',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devkornerinfos',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
